### PR TITLE
Filter: INSTANCE OF

### PR DESCRIPTION
**Pull request by Strontium-90**
Assert Entity is instance of class.

### CODE REVIEW

**Comment by Nyholm** [comment]
Im not too sure Im familiar with the `INSTANCE OF` syntax in MySql(?). Can you link the documentation?

**Comment by Strontium-90** [comment]
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#query-the-type

**Comment by Nyholm** [comment]
Okey, Thank you for the link. 

I appreciate your PRs.

**Comment by Nyholm** [comment]
I've tagged version 0.6.1 which includes this feature.

**Pull request merged**
