### PR TITLE
Build from GitHub CI

### PR DESCRIPTION
**Pull request by peter-gribanov**
Travis CI takes a very long time to build. Building and testing just one commit can take up to 16 hours. It [looks](https://travis-ci.community/t/builds-hang-in-queued-state/10250/6) like this problem is related to the migration of https://travis-ci.org to https://travis-ci.com. The https://travis-ci.org domain will be closed later than December 31st, 2020.

I faced a similar problem on other projects and failed to migrate them to https://travis-ci.com. Migrating to the https://travis-ci.com can create [new problems](https://travis-ci.community/t/builds-hang-in-queued-state/10250/28). We are migrating our projects to [GitHub CI](https://github.com/features/actions) and are satisfied with the result.

<details>
  <summary>build took more than 9 hours</summary>

</details>

<details>
  <summary>build took more than 11 hours</summary>

</details>

### CODE REVIEW

**Comment by peter-gribanov** [comment]
@Nyholm can you check the GitHub Actions settings?

<details>
  <summary>Expected actions permissions</summary>

</details>

**Comment by Nyholm** [comment]
The first PR to actions is always tricky. They will not run because they are not defined in the source (not fork). 

I suggest merging this now and fix the issues in a following PR when we see that they run.

**Comment by Nyholm** [comment]
I see that the actions are running now.  =)

**Comment by peter-gribanov** [comment]
@Nyholm thanks

**Pull request merged**
