### PR TITLE
Build from GitHub CI

### PR DESCRIPTION
**Pull request by peter-gribanov**
Do changes from #250 for master.

### CODE REVIEW

**Comment by peter-gribanov** [comment]
> continuous-integration/travis-ci Expected — Waiting for status to be reported

@Nyholm this job is stuck. It [looks](https://travis-ci.community/t/pr-build-status-stuck-at-continuous-integration-travis-ci-expected-waiting-for-status-to-be-reported/7220/2) like this a [Branch protection rule](https://user-images.githubusercontent.com/1954436/101055890-7095ca80-359b-11eb-8baf-8e74fe91c846.png) setting prohibits merging branches without a positive response from Travis CI, which we refuse in this request. Can you check it out?

**Comment by Nyholm** [comment]
I thought I've answered this. Im sorry. 

I've updated the branch protection now

**Comment by Nyholm** [comment]
You may now update the branch protection rules yourself if you want to

**Comment by peter-gribanov** [comment]
@Nyholm thanks

**Comment by peter-gribanov** [comment]
> You may now update the branch protection rules yourself if you want to

@Nyholm branch protection rules are available in the project settings, which i do not have access to now. I don't really need the project settings. Although you still have to manage the list of checkers. We need to change the list of checkers for version 1.1 and we will need to change the list of checks after release 2.0. At the end of 2021, i would plan to abandon PHP 7.3, add support for PHP 8.1 and a new major release with a change in the list of checkers.

image

**Pull request merged**
