### PR TITLE
Added NotIn Specification

### PR DESCRIPTION
**Pull request by drewsonian**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. The NotIn was missing. Nice that you included tests and a factory class. 

I'm hesitating for merging this one though. Are there any differences between the following specifications?

```php
$a = new NotIn('foo', array(1,2,3));
$b = new Not(new In('foo' array(1,2,3)));
```

**Comment by drewsonian** [comment]
That's interesting, I hadn't thought of that.  I just tested

```
$b = new Not(new In('foo' array(1,2,3)));
```
and it works correctly.

Modified the PR to just add the factory class.

**Comment by Nyholm** [comment]
Okey. That's great!

Would you mind [squashing your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

**Comment by drewsonian** [comment]
Thanks for bearing with me while I learn more about git, etc... Obviously I'm getting a few things wrong, sorry your inbox is probably filling with notifications.

**Comment by Nyholm** [comment]
No worries. I think you are doing great. I'm happy for all the notifications =)

If you look at the [diff](https://github.com/Happyr/Doctrine-Specification/pull/104/files) for this PR, it seams like you have added the method 3 times.

**Comment by drewsonian** [comment]
Yeah, I noticed that. My issue I'm new to the git command line and rebasing through that.  I'm spoiled with PHPStorm :-)

**Comment by Nyholm** [comment]
haha, okey. It's good to bring up the console once in a while. Me too gets too comfortable with PHPStorm time to time.

**Comment by drewsonian** [comment]
Closing and just starting from scratch...

**Comment by Nyholm** [comment]
:+1:

**Comment by drewsonian** [comment]
#106 covers this.

**Pull request closed without merging**
