### PR TITLE
Change access of protected properties to private

### PR DESCRIPTION
**Pull request by peter-gribanov**

### CODE REVIEW

**Comment by Nyholm** [comment]
I see that you are preparing for a 2.0. That is awesome =)

**Comment by peter-gribanov** [comment]
> I see that you are preparing for a 2.0. That is awesome =)

I haven't done this project for a long time. Despite the fact that I use this project all the time, I have no idea how to improve it.
I want to make a major release to remove deprecated code, add type hinting and add support for PHP 8.

**Comment by Nyholm** [comment]
That is great then. That will make upgrading easy.

**Comment by peter-gribanov** [comment]
rebuild

**Review by Nyholm — APPROVED** [review]

**Pull request merged**
