### PR TITLE
Specification Interface for Happyr/Doctrine-Specification#53

### LINKED ISSUE #53: define an interface for the specification repository
I have a case with
class UserGroupRepository extends NestedTreeRepository

so it is hard to make it extend also the base class, however there is not an interface

### PR DESCRIPTION
**Pull request by thundo**
Created EntitySpecificationRepositoryInterface. Fixes #53

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 
Can you tell my your thoughts about not including getQuery and setAlias in the interface?

**Comment by thundo** [comment]
You're welcome. 

About `getQuery` I did not find it in Doctrine `ObjectRepository` interface so, for consistency, I didn't add it. About [get|set]Alias I'm not really sure, what's their use case outside the bundle?

What do you think?

**Comment by Nyholm** [comment]
Okey, fair enough.

What is your intended use case for the interface? I'm guessing you want to use the Specification pattern but not use the current implementation of the EntitySpecificationTrait.

**Comment by thundo** [comment]
Actually I do use the provided Trait, but while injecting a `EntitySpecificationRepository` in another service, I'd like to rely on its interface instead of its implementation.

**Comment by Nyholm** [comment]
Okey. Let's include `getQuery` in the interface because that is something you also may want to use in your other service.

**Comment by thundo** [comment]
Anything else blocking the merge?

**Comment by Nyholm** [comment]
Sorry. I did not get any notification that you updated the PR. 

Thank you for this. Really appreciated.

**Comment by thundo** [comment]
Thank you for your openness. Cheers

**Comment by Nyholm** [comment]
I just tagged version 0.7.1

**Comment by thundo** [comment]
Nice. Thank you!

**Pull request merged**
