### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by KDederichs**
Allow Symfony 6 and add PHP 8.1 to test matrix

### CODE REVIEW

**Comment by KDederichs** [comment]
Fixes #314

**Comment by peter-gribanov** [comment]
PHPSpec not support PHP 8.1 https://github.com/phpspec/phpspec/issues/1406

**Comment by KDederichs** [comment]
Good to know, removed that for now then :)

**Comment by peter-gribanov** [comment]
Please add Symfony 6 compatibility check to the GitHub Action config:

```yml
- php-version: '8.0'
    dependencies: highest
    variant: 'doctrine/orm:~2.7 symfony/symfony:^6.0'
```

**Comment by KDederichs** [comment]
Sure, also increased the PHP CS Fixer PHP Version, seems like that needs 7.4 now

**Comment by peter-gribanov** [comment]
Please try to change
```diff
-    variant: 'doctrine/orm:~2.7 symfony/symfony:^6.0'
+    variant: 'doctrine/orm:~2.7 symfony/property-access:^6.0'
```

**Comment by KDederichs** [comment]
Done, hope that fixes it cause otherwise PHPSpec needs to be updated as well?

**Comment by peter-gribanov** [comment]
Thanks for your work :+1:

**Comment by peter-gribanov** [comment]
Released in [v2.0.2](https://github.com/Happyr/Doctrine-Specification/releases/tag/v2.0.2).

**Pull request merged**
