### PR TITLE
Created AbstractJoin and added innerJoin

### PR DESCRIPTION
**Pull request by Nyholm**
Added innerJoin. To avoid too much code duplication I also created an AbstractJoin.

### CODE REVIEW

**Comment by Nyholm** [comment]
Ping @drewsonian. What do you think?

**Comment by drewsonian** [comment]
I like it - it really cuts down on duplicating code.  Further, I didn't realize that you could do this in PHP:

```
$qb->*$join*(sprintf('%s.%s', $dqlAlias, $this->field), $this->newAlias);
```

**Comment by Nyholm** [comment]
It's dynamic functions. It is worse for autocomplete and caching but it can (like in this example) make your code very clean.

**Comment by drewsonian** [comment]
Actually, I think I've seen it before, but hadn't seen a good use case until now. :-)

**Pull request merged**
